name: Repository dispatch for fork

on:
  fork

jobs:
  repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: rrachitha/support-repo-1
          event-type: create_gh_action
          