name: Test Action

on:
  create


jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: rrachitha/support-repo
          event-type: custom_event_type
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'